name: CI

on:
  workflow_dispatch: # On manual trigger
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
      uses: denoland/setup-deno@v1

      - name: Crypto
        run: deno task crypto

      - name: Equities
        run: deno task equities

      - name: ETFs
        run: deno task etfs

      - name: Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "assets: update"
          git push
